name: Release

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'oracle'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run JReleaser
        run: |
          ./gradlew jreleaserConfig
          ./gradlew jreleaserFullRelease
        env:
          JRELEASER_GITHUB_TOKEN: ${{ github.token }}
          JRELEASER_DOCKER_GHCR_USERNAME: ${{ github.actor }}
          JRELEASER_DOCKER_GHCR_PASSWORD: ${{ github.token }}
