name: release

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Configure build steps as you'd normally do

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'oracle'
          cache: gradle

      # Create a release

      - name: Run JReleaser
        run: |
          ./gradlew jreleaserConfig
          ./gradlew jreleaserFullRelease
