name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      issues: write
      id-token: write

    env:
      JRELEASER_GITHUB_TOKEN: ${{ github.token }}
      JRELEASER_DOCKER_GHCR_USERNAME: ${{ github.actor }}
      JRELEASER_DOCKER_GHCR_PASSWORD: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run JReleaser Release
        run: |
          ./gradlew jreleaserFullRelease --info
